AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless app that writes to DynamoDB

Resources:
  AppFunction1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: serverless-dynamodb-function
      Handler: app/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 300
      Environment:
        Variables:
          TABLE_NAME: !Ref ServerlessAppTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ServerlessAppTable
      Events:
       app1:
          Type: Api
          Properties:
            Path: /app1
            Method: post

  ServerlessAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ServerlessAppTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-architecture-web-bucket
      WebsiteConfiguration:
        IndexDocument: index.html

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StaticWebsiteBucket}/*"

Outputs:
  StaticWebsiteBucketName:
    Value: !Ref StaticWebsiteBucket
    Description: Name of the S3 bucket for static website
  WebsiteURL:
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
    Description: URL for the static website hosted on S3
