version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-architecture"
s3_prefix = "serverless-architecture"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
