name: Deploy Serverless Architecture

on:
  push:
      branches: ['tmp'] # temporary stop builds

env:
    AWS_REGION: 'eu-west-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v3

        - uses: actions/setup-python@v3

        - uses: aws-actions/setup-sam@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Build SAM Application
          run: sam build

        - name: Package SAM
          run: sam package --template-file template.yaml --output-template-file template.packed.yaml --resolve-s3 --region eu-west-1

        - name: Deploy
          run: sam deploy --no-fail-on-empty-changeset --no-confirm-changeset --config-file "./samconfigs/samconfig.toml" --template-file template.packed.yaml --stack-name "serverless-architecture" --region eu-west-1 --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
